server:
  port: 8080
  tomcat:
    connection-timeout: 2000ms # 2초
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jco_community
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # HikariCP의 최대 커넥션 풀 크기 설정

  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발 환경에서만 사용
      jdbc:
        batch_size: 1000     # 배치 처리 사이즈
      properties:
        hibernate.format_sql: true         # SQL 포맷팅
        hibernate.use_sql_comments: true   # SQL 주석 활성화
    show-sql: true              # SQL 출력 활성화
    generate-ddl: true          # DDL 자동 생성 (개발 환경에 적합)



logging:
  level:
    root: INFO
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql: TRACE